package Clases;

import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseListener;

public class VistaCS extends javax.swing.JFrame {

    /**
     * Creates new form VistaCS
     *
     * @param titulo
     */
    public VistaCS(String titulo) {
        super(titulo);
        initComponents();
        setLocationRelativeTo(null);
        this.jButtonVoltearCarta.setEnabled(false);
    }

    public void mostrarFotoCarta(String icon) {
        this.jLabelIconCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon)));
    }

    public void vistaMazoVacio() {
        this.jLabelMazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mazoVacio.png")));
    }

    public void estadoDefault() {
        this.jButtonIniciar.setEnabled(true);
        this.jButtonVoltearCarta.setEnabled(false);
        this.mostrarCarta("");
        this.actualizarScore(0);
    }

    public void partidaEnCurso(String name, int score) {
        this.mostrarNombreJugador(name);
        this.actualizarScore(score);
        this.jButtonIniciar.setEnabled(false);
        this.jButtonVoltearCarta.setEnabled(true);
        this.jLabelResultado.setText("");
        this.jLabelCartaText.setText("");
        this.jLabelCartasRestantes.setText("");
        this.jLabelIconCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nocard.png")));
        this.jLabelMazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartaoculta.jpg")));
    }

    public void actualizarCartasRestantes(int q) {
        this.jLabelCartasRestantes.setText("Cartas restantes: " + q);
    }

    public String preguntarNombre() {
        return JOptionPane.showInputDialog("Ingresar nombre de jugador\n(Hasta 16 caractéres)");
    }

    public void mostrarNombreJugador(String nombre) {
        this.jLabelNombreJugador.setText("Jugador: " + nombre);
    }

    public void mostrarMensajeError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void mostrarCarta(String carta) {
        this.jLabelCartaText.setText(carta);
    }

    public void actualizarScore(int score) {
        this.jLabelPuntos.setText(String.valueOf(score));
        if (score == 0) {
            this.jLabelPuntos.setForeground(new Color(255, 255, 255));
        } else if (score < 19) {
            this.jLabelPuntos.setForeground(new Color(235, 64, 52));
        } else if (score > 40) {
            this.jLabelPuntos.setForeground(new Color(0, 201, 178));
        } else if (score > 30) {
            this.jLabelPuntos.setForeground(new Color(0, 201, 74));
        } else if (score > 19) {
            this.jLabelPuntos.setForeground(new Color(240, 121, 62));
        }
    }

    public void tamanioFuenteVoltearCarta(int px) {
        if (this.jButtonVoltearCarta.isEnabled()) {
            this.jButtonVoltearCarta.setFont(new Font("Tahoma", 1, px));
        } else {
            this.jButtonVoltearCarta.setFont(new Font("Tahoma", 1, 14));
        }
    }

    public void clickVoltearCarta() {
        this.jButtonVoltearCarta.setBackground(new Color(24, 115, 48));
    }

    public void finPartida(int score) {
        this.jLabelResultado.setText("Fin de la partida | Puntaje final: " + String.valueOf(score));
        this.jButtonVoltearCarta.setEnabled(false);
        this.jButtonIniciar.setEnabled(true);
    }

    public void voltearCartaListener(ActionListener al) {
        this.jButtonVoltearCarta.addActionListener(al);
    }

    public void iniciarPartidaListener(ActionListener al) {
        this.jButtonIniciar.addActionListener(al);
    }

    public void hoverVoltearCartaListener(MouseListener al) {
        this.jButtonVoltearCarta.addMouseListener(al);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltearCarta = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jLabelCartasRestantes = new javax.swing.JLabel();
        jLabelPuntos = new javax.swing.JLabel();
        jLabelCartaText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMazo = new javax.swing.JLabel();
        jLabelIconCarta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNombreJugador = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 470));
        setMinimumSize(new java.awt.Dimension(500, 470));
        setPreferredSize(new java.awt.Dimension(500, 470));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonVoltearCarta.setBackground(new java.awt.Color(0, 51, 51));
        jButtonVoltearCarta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltearCarta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltearCarta.setText("Voltear carta");
        jButtonVoltearCarta.setFocusPainted(false);
        getContentPane().add(jButtonVoltearCarta);
        jButtonVoltearCarta.setBounds(160, 270, 170, 44);

        jButtonIniciar.setBackground(new java.awt.Color(0, 51, 51));
        jButtonIniciar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setText("Iniciar partida");
        jButtonIniciar.setFocusPainted(false);
        getContentPane().add(jButtonIniciar);
        jButtonIniciar.setBounds(160, 10, 170, 22);

        jLabelCartasRestantes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCartasRestantes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCartasRestantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCartasRestantes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabelCartasRestantes);
        jLabelCartasRestantes.setBounds(160, 240, 170, 20);

        jLabelPuntos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPuntos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPuntos.setText("0");
        jLabelPuntos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelPuntos);
        jLabelPuntos.setBounds(180, 350, 130, 40);

        jLabelCartaText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCartaText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCartaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCartaText.setText(" ");
        getContentPane().add(jLabelCartaText);
        jLabelCartaText.setBounds(190, 70, 120, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Puntos:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 330, 130, 14);

        jLabelMazo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cartaoculta.jpg"))); // NOI18N
        jLabelMazo.setMaximumSize(new java.awt.Dimension(79, 130));
        jLabelMazo.setMinimumSize(new java.awt.Dimension(79, 130));
        jLabelMazo.setPreferredSize(new java.awt.Dimension(79, 130));
        jLabelMazo.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabelMazo);
        jLabelMazo.setBounds(160, 90, 80, 130);

        jLabelIconCarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nocard.png"))); // NOI18N
        getContentPane().add(jLabelIconCarta);
        jLabelIconCarta.setBounds(250, 90, 80, 130);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(70, 60, 337, 12);

        jLabelNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreJugador.setText(" ");
        getContentPane().add(jLabelNombreJugador);
        jLabelNombreJugador.setBounds(147, 40, 200, 14);

        jLabelResultado.setForeground(new java.awt.Color(0, 204, 0));
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultado.setText(" ");
        getContentPane().add(jLabelResultado);
        jLabelResultado.setBounds(86, 410, 310, 14);

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.jpg"))); // NOI18N
        getContentPane().add(jFondo);
        jFondo.setBounds(-6, -6, 510, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonVoltearCarta;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCartaText;
    private javax.swing.JLabel jLabelCartasRestantes;
    private javax.swing.JLabel jLabelIconCarta;
    private javax.swing.JLabel jLabelMazo;
    private javax.swing.JLabel jLabelNombreJugador;
    private javax.swing.JLabel jLabelPuntos;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
